version: "3"

services:

  pipelines:
    build: .
    image: nli-data-pipelines
    ports:
    - "5000:5000"
    volumes:
    - ".:/pipelines"
    - "data-cache:/pipelines/data/cache"
    command:
    - server

volumes:
  data-cache:
