{{ if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pipelines
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.gkeNodePool | default "default-pool" | quote }}
      containers:
      - image: {{ .Values.image | default "orihoch/nli-data-pipelines" | quote }}
        name: pipelines
        ports:
        - containerPort: 5000
        args:
        - server
        volumeMounts:
        - name: "pipelines-data"
          mountPath: "/pipelines/data"
        {{ if .Values.enableGcs }}
        env:
        - {"name": "GCS_PROJECT", "value": {{ .Values.GCS_PROJECT }}}
        - {"name": "GCS_IMAGES_BUCKET", "value": {{ .Values.GCS_IMAGES_BUCKET }}}
        - name: GCS_SERVICE_ACCOUNT_B64_KEY
          valueFrom:
            secretKeyRef:
              name: env-vars
              key: "GCS_SERVICE_ACCOUNT_B64_KEY"
        - {"name": "DOWNLOAD_IMAGES_NUM_THREADS", "value": {{ .Values.DOWNLOAD_IMAGES_NUM_THREADS | quote }}}
        {{ end }}
      volumes:
      - name: pipelines-data
        hostPath:
          path: /var/pipelines-data
{{ end }}
