{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-d
data:
  default.conf: |
    server {
        listen 80;
        server_name  _;
        include /etc/nginx/conf.d/healthcheck.inc;
        include /etc/nginx/conf.d/services.inc;
    }

  services.inc: |
    {{ if .Values.enableData }} include /etc/nginx/conf.d/data.inc; {{ end }}
    {{ if .Values.enablePipelines }} include /etc/nginx/conf.d/pipelines.inc; {{ end }}
    {{ if .Values.enablePipelines2 }} include /etc/nginx/conf.d/pipelines2.inc; {{ end }}

  healthcheck.inc: |
    location = / {
        return 200 'it works!';
        add_header Content-Type text/plain;
    }

  pipelines.inc: |
    location /pipelines/ {
        proxy_pass http://pipelines:5000/;
    }

  pipelines2.inc: |
    location /pipelines2/ {
        proxy_pass http://pipelines2:5000/;
    }

  data.inc: |
    location /data/ {
      root /pipelines;
      autoindex on;
    }
{{ end }}
