{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: nginx}
spec:
  replicas: {{ .Values.replicas | default "1" }}
  template:
    metadata:
      labels: {app: nginx}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.gkeNodePool | default "default-pool" | quote }}
      affinity:
        # nginx must be on the same as pipelines - to have access to the data files
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["pipelines"]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ .Values.image | default "nginx:alpine" | quote }}
        name: nginx
        ports:
        - {containerPort: 80}
        volumeMounts:
        - name: nginx-conf-d
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: pipelines-data
          mountPath: /pipelines/data
      volumes:
      - name: nginx-conf-d
        configMap:
          name: nginx-conf-d
      - name: pipelines-data
        hostPath:
          path: /var/pipelines-data
{{ end }}
