{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    name: "80"
  - port: 443
    name: "443"
  - port: 8937
    name: "8937"
    targetPort: 9200
  selector:
    app: nginx
  type: LoadBalancer
{{ end }}
