{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: "9200"
  - port: 9300
    name: "9300"
{{ end }}