{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-conf
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 1
{{ end }}
