{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name | default "adminer"}}
spec:
  selector:
    app: {{.Values.name | default "adminer"}}
  ports:
  - port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name | default "adminer"}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name | default "adminer"}}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.gkeNodePool | default "default-pool" | quote }}
      containers:
      - image: {{.Values.image | default "adminer:4.3.1-standalone"}}
        name: {{.Values.name | default "adminer"}}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.001"
            memory: "10Mi"
          limits:
            cpu: "0.05"
            memory: "100Mi"
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          httpGet:
            path: /
            port: 8080
{{ end }}
